"""Change in the seasons table to prevent pk ambiguity in Seasons model

Revision ID: d2f93783ed4e
Revises: afbdce4d41a8
Create Date: 2025-06-16 17:11:32.704435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2f93783ed4e'
down_revision: Union[str, None] = 'afbdce4d41a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('seasons', sa.Column('id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_seasons_id'), 'seasons', ['id'], unique=False)
    op.create_unique_constraint('uq_anime_season', 'seasons', ['animeId', 'seasonNumber'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_anime_season', 'seasons', type_='unique')
    op.drop_index(op.f('ix_seasons_id'), table_name='seasons')
    op.drop_column('seasons', 'id')
    # ### end Alembic commands ###
